config/routes.rb
Rails.application.routes.draw do
    
  get 'segmentation_workspace', to: 'segmentation_workspace#index'
  get 'segmentation_workspace/:id/run', to: 'segmentation_workspace#run', as: 'segmentation_workspace_run'

  resources :segmentations, except: [:show] do
    resources :segmentation_clauses, except: [:index, :show, :create], path: 'clauses', as: 'clause'
  end
  match '/segmentations/:segmentation_id/clauses', to: 'segmentation_clauses#create', via: :post, as: 'segmentation_clauses'
  # resources :segmentation_clauses

  resources :contacts, except: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'contacts#index'
end

app/models/segmentation.rb
class Segmentation < ApplicationRecord
    validates :name, presence: :true
    
    has_many :segmentation_clauses, dependent: :destroy

    def readable_conditions
        segmentation_clauses.map{ |clause| clause.unsecure_where }.join " AND "
    end

    def search! activerecord_class
        result = activerecord_class.constantize
        segmentation_clauses.each { |comp| result = result.where(comp.mount_where, comp.formated_value)}
        return result
    end
end

app/controllers/segmentations_controller.rb
class SegmentationsController < ApplicationController
  before_action :set_segmentation, only: [:edit, :update, :destroy]

  # GET /segmentations
  # GET /segmentations.json
  def index
    @segmentations = Segmentation.all
  end

  def new
    @segmentation = Segmentation.new
  end

  def edit
  end

  # equivalent to 'add_conditions'
  def create
    @segmentation = Segmentation.new(segmentation_params)

    respond_to do |format|
      if @segmentation.save
        format.html { redirect_to new_segmentation_clause_path @segmentation }
        format.json { render :show, status: :created, location: @segmentation }
      else
        format.html { render :new }
        format.json { render json: @segmentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /segmentations/1
  # PATCH/PUT /segmentations/1.json
  def update
    respond_to do |format|
      if @segmentation.update(segmentation_params)
        format.html { flash[:notice]= 'Segmentation was successfully updated.'; render :edit }
        format.json { render :show, status: :ok, location: @segmentation }
      else
        format.html { render :edit }
        format.json { render json: @segmentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /segmentations/1
  # DELETE /segmentations/1.json
  def destroy
    @segmentation.destroy
    respond_to do |format|
      format.html { redirect_to segmentations_url, notice: 'Segmentation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_segmentation
      @segmentation = Segmentation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def segmentation_params
      params.require(:segmentation).permit(:name)
    end
end

app/helpers/segmentation_helper.rb
module SegmentationHelper
end

app/helpers/segmentations_helper.rb
module SegmentationsHelper
end

app/views/segmentations/_clauses.html.erb
<% if segmentation_clauses %>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Segmentation</th>
        <th>Comparison opration</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% segmentation_clauses.each do |segmentation_clause| %>
        <tr>
          <td><%= segmentation_clause.segmentation_name %> </td>
          <td><%= segmentation_clause.readable_where %></td>
          <td><%= link_to 'Edit', edit_segmentation_clause_path(segmentation_clause.segmentation, segmentation_clause)%></td>
          <td><%= link_to 'Destroy', segmentation_clause_path(segmentation_clause.segmentation, segmentation_clause) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>

app/views/segmentations/_form.html.erb
<%= form_for(segmentation) do |f| %>

  <% if segmentation.errors.any? %>
    <div class="alert alert-danger">
      <p class="lead">Correct the folowing <%= pluralize(segmentation.errors.count, "error") %>:</p>

      <ul>
        <% segmentation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= link_to '<- Back to list', segmentations_path, {class: "btn btn btn-info", role: "button"} %>
    <%= yield %>
  </div>
<% end %>

app/views/segmentations/edit.html.erb
<h1>Editing Segmentation</h1>

<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-md-12">
        <%= render 'form', segmentation: @segmentation do%>
            <%= submit_tag 'Update', class: "btn btn-info" %>
            <%= link_to 'Add conditions', new_segmentation_clause_path(@segmentation), {class: "btn btn btn-success", role: "button"}  %>
        <% end %>
    </div>
</div>

<section class="detail-list">
    <h1>Conditions:</h1>
    <%= render 'clauses', segmentation_clauses: @segmentation.segmentation_clauses %>
<section>

app/views/segmentations/index.html.erb
<h1>Segmentations</h1>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @segmentations.each do |segmentation| %>
        <tr>
          <td><%= segmentation.name %></td>
          <td><%= link_to 'Edit', edit_segmentation_path(segmentation), class: "btn btn-default btn-sm" %></td>
          <td><%= link_to 'Destroy', segmentation, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New Segmentation', new_segmentation_path, {class: "btn btn-success"} %>

app/views/segmentations/new.html.erb
<h1>New Segmentation</h1>

<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col-md-12">
        <%= render 'form', segmentation: @segmentation do%>
            <%= submit_tag 'Add conditions', class: "btn btn-success" %>
        <% end %>
    </div>
</div>