config/routes.rb
Rails.application.routes.draw do
    
  get 'segmentation_workspace', to: 'segmentation_workspace#index'
  get 'segmentation_workspace/:id/run', to: 'segmentation_workspace#run', as: 'segmentation_workspace_run'

  resources :segmentations, except: [:show] do
    resources :segmentation_clauses, except: [:index, :show, :create], path: 'clauses', as: 'clause'
  end
  match '/segmentations/:segmentation_id/clauses', to: 'segmentation_clauses#create', via: :post, as: 'segmentation_clauses'
  # resources :segmentation_clauses

  resources :contacts, except: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'contacts#index'
end

app/controllers/segmentation_workspace_controller.rb
class SegmentationWorkspaceController < ApplicationController
  def index
    @segmentations = Segmentation.all
  end

  def run
    @segmentation = Segmentation.find(params[:id])
    @contacts = @segmentation.search! "Contact"
  end
end

app/helpers/segmentation_workspace_helper.rb
module SegmentationWorkspaceHelper
end

app/views/segmentation_workspace/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Segmentations for Contact</h1>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Conditions</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @segmentations.each do |segmentation| %>
        <tr>
          <td><%= segmentation.name %></td>
          <td><%= segmentation.readable_conditions %></td>
          <td><%= link_to 'Run!', segmentation_workspace_run_path(segmentation), {class: "btn btn btn-success", role: "button"}  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/segmentation_workspace/run.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts filtered by '<%= @segmentation.name %>'</h1>

<p>
    This filter is using the folowing conditions
    <ul>
        <% for clause in @segmentation.segmentation_clauses %>
            <li> <%= clause.unsecure_where %></li>
        <% end %>
    </ul>
<p>

<div class="actions">
    <%= link_to 'Edit Filter', edit_segmentation_path(@segmentation), {class: "btn btn btn-info", role: "button"}  %>
    <%= link_to 'Reload', segmentation_workspace_run_path(@segmentation), {class: "btn btn btn-info", role: "button"}  %>
<div>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Age</th>
        <th>State</th>
        <th>Occupation</th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.name %></td>
          <td><%= contact.email %></td>
          <td><%= contact.age %></td>
          <td><%= contact.state.initials %></td>
          <td><%= contact.occupation %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>