config/routes.rb
Rails.application.routes.draw do
    
  get 'segmentation_workspace', to: 'segmentation_workspace#index'
  get 'segmentation_workspace/:id/run', to: 'segmentation_workspace#run', as: 'segmentation_workspace_run'

  resources :segmentations, except: [:show] do
    resources :segmentation_clauses, except: [:index, :show, :create], path: 'clauses', as: 'clause'
  end
  match '/segmentations/:segmentation_id/clauses', to: 'segmentation_clauses#create', via: :post, as: 'segmentation_clauses'
  # resources :segmentation_clauses

  resources :contacts, except: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'contacts#index'
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :age, :email, :occupation, presence: true

  belongs_to :state
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { success_form_redirect 'Contact was successfully created.' }
        format.json { render :index, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { success_form_redirect 'Contact was successfully updated.'}
        format.json { render :index, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_path, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :age, :state_id, :occupation)
    end

    def success_form_redirect notice
        if params[:save_and_add].nil?
          redirect_to @contact, notice: notice
        else
          redirect_to new_contact_path, notice: notice
        end
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for(contact) do |f| %>
  <% if contact.errors.any? %>
    <div class="alert alert-danger">
      <p class="lead">Correct the folowing <%= pluralize(contact.errors.count, "error") %>:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :age %>
    <%= f.number_field :age, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :state %>
    <%= f.collection_select(:state_id, State.all, :id, :name, {}, {class: "form-control"}) %>
  </div>

  <div class="form-group">
    <%= f.label :occupation %>
    <%= f.text_field :occupation, class: "form-control" %>
  </div>

  <div class="actions">
    <%= link_to '<- Back to list', contacts_path, {class: "btn btn btn-info", role: "button"}  %>
    <%= submit_tag 'Save and create another', name: 'save_and_add', class: "btn btn-success" %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<p id="notice"><%= flash[:notice] %></p>

<div class="row">
    <div class="col-md-12">
        <h1>Editing Contact</h1>

        <%= render 'form', contact: @contact %>
    </div>
</div>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Age</th>
        <th>State</th>
        <th>Occupation</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td><%= contact.name %></td>
          <td><%= contact.email %></td>
          <td><%= contact.age %></td>
          <td><%= contact.state.initials %></td>
          <td><%= contact.occupation %></td>
          <td><%= link_to 'Edit', edit_contact_path(contact), class: "btn btn-default btn-sm" %></td>
          <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-sm" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'New Contact', new_contact_path, {class: "btn btn-success"} %>

app/views/contacts/new.html.erb
<p id="notice"><%= flash[:notice] %></p>

<div class="row">
    <div class="col-md-12">
        <h1>New Contact</h1>

        <%= render 'form', contact: @contact %>     
    </div>
</div>