config/routes.rb
Rails.application.routes.draw do
    
  get 'segmentation_workspace', to: 'segmentation_workspace#index'
  get 'segmentation_workspace/:id/run', to: 'segmentation_workspace#run', as: 'segmentation_workspace_run'

  resources :segmentations, except: [:show] do
    resources :segmentation_clauses, except: [:index, :show, :create], path: 'clauses', as: 'clause'
  end
  match '/segmentations/:segmentation_id/clauses', to: 'segmentation_clauses#create', via: :post, as: 'segmentation_clauses'
  # resources :segmentation_clauses

  resources :contacts, except: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'contacts#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Segmentacao</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= csrf_meta_tags %>
    </head>

    <body>

        <div id="wrapper" class="active">  
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul id="sidebar_menu" class="sidebar-nav">
                   <li class="sidebar-brand"><a id="menu-toggle" href="#">Menu<span id="main_icon" class="glyphicon glyphicon-align-justify"></span></a></li>
                </ul>
                <ul class="sidebar-nav" id="sidebar">
                  <li><a href="<%= contacts_url %>">Contacts<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
                   <ul class="sidebar-nav" id="sidebar">
                        <li><a href="<%= segmentations_url %>">Build<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
                        <li><a href="<%= segmentation_workspace_url %>">Run<span class="sub_icon glyphicon glyphicon-link"></span></a></li>
                   </ul>
                </ul>
              </div>
                  
              <!-- Page content -->
              <div id="page-content-wrapper">
                <div class="page-content inset">
                    <%= yield %>
                </div>
            </div>
        </div>
        <%= javascript_include_tag "jquery_ujs" %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </body>
</html>